### ISSUE TITLE
Migrate to GDBus

### ISSUE THREAD

**Issue by worldofpeace** [elementary/pantheon-agent-geoclue2#24]
> dbus-glib is a deprecated API for use of D-Bus from GLib applications. Do not use it in new code.
Since version 2.26, GLib's accompanying GIO library provides a high-level API for D-Bus, "GDBus", based on an independent reimplementation of the D-Bus protocol. The maintainers of D-Bus recommend that GLib applications should use GDBus instead of dbus-glib.

**Comment by tintou** [comment]
Fixed in master, we weren't even using dbus-glib so no idea why it got added as a dependency
Thanks for watching this :)

**Comment by worldofpeace** [comment]
@tintou Thanks a lot. :+1:
