### ISSUE TITLE
agent just exits 10 seconds after launch (quiet timeout?) on fedora

### ISSUE THREAD

**Issue by decathorpe** [elementary/pantheon-agent-geoclue2#26]
I ran into issues when trying to use applications that use location services on Pantheon/fedora. It looks like the `/usr/libexec/geoclue2-1-pantheon/pantheon-agent-geoclue2` process just terminates after ten seconds every time it is launched. No messages are printed to stdout or stderr, it just exits after exactly 10 seconds (so it might be related to a quiet timeout). Exit code is a normal 0 (which doesn't help either).

```
$ time /usr/libexec/geoclue2-1-pantheon/pantheon-agent-geoclue2 

real	0m10.051s
user	0m0.032s
sys	0m0.007s
```

**Comment by tintou** [comment]
It is normal, the agent will be started on-demand and then will shutdown if nothing happens

**Comment by akostadinov** [comment]
FYI #30
