### ISSUE TITLE
Agent is going away, use Portals

### ISSUE THREAD

**Issue by danirabbit** [elementary/pantheon-agent-geoclue2#32]
The GeoClue maintainer has stated that in future versions of GeoClue [the agent API is going away](https://www.collabora.com/news-and-blog/blog/2018/10/12/recently-in-geoclue/) and the expectation is that we using [portals](http://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Location)

**Comment by davidmhewitt** [comment]
Been looking into this recently. The version of geoclue required on the host side is not new enough in `bionic` and as a result `xdg-desktop-portals-gtk` is not compiled with support for the location portal. So unless we end up backporting those, this will be a `focal` only feature.

Additionally, the version of geoclue in the current `org.freedesktop.Sdk` (currently 19.08.7) is not new enough for the `GClue.Simple` class to be portal aware. There hasn't been a geoclue release that incorporates this code yet, so it could be a while before the sdk is updated to include it.

**Comment by janxkoci** [comment]
Is this why location reporting stopped working in all apps recently?
