### ISSUE TITLE
Always ask when privacy mode is enabled

### ISSUE THREAD

**Issue by danirabbit** [elementary/pantheon-agent-geoclue2#5]
I think that follows logically no?

Launchpad Details: [#LP1667946](https://bugs.launchpad.net/bugs/1667946) Daniel Fore - 2017-02-25 16:45:33 +0000

**Comment by danrabbit** [comment]
I think that makes sense. If you're in "private mode", then I expect that you don't want to default to sharing data with applications, right?

Launchpad Details: [#LPC](https://bugs.launchpad.net/pantheon-agent-geoclue2/+bug/1667946/comments/1) Neal Gompa - 2017-02-25 17:05:15 +0000

**Comment by danrabbit** [comment]
Agree with this, although do we need to change the wording or have some common theming that makes it clear that it's asking because you're in privacy mode?

Launchpad Details: [#LPC](https://bugs.launchpad.net/pantheon-agent-geoclue2/+bug/1667946/comments/2) David Hewitt - 2017-02-25 17:46:38 +0000

**Comment by cassidyjames** [comment]
At some point we reverted "Privacy Mode" to just a toggle for "History". It might be less clear that this is related now. Do we want to go back to calling it a "Privacy Mode," add a separate "Privacy Mode" that sets the History setting as well as some other things, or…?
