### ISSUE TITLE
install binary to LIBEXECDIR instead of hardcoding PREFIX/lib

### ISSUE THREAD

**Issue by decathorpe** [elementary/pantheon-agent-geoclue2#7]
The following lines in `CMakeLists.txt` hard-code the location of the binary to PREFIX/lib. This is the wrong location on many distributions.

```
set (LIBDIR "${CMAKE_INSTALL_PREFIX}/lib")
set (EXECDIR "${LIBDIR}/geoclue2-1-pantheon")
```

You should be able to preserve the current behavior on elementary and also make it install to the right location by replacing those two lines with

```
include (GNUInstallDirs)
set (EXECDIR "${CMAKE_INSTALL_FULL_LIBEXECDIR}/geoclue2-1-pantheon")
```

just like it is done in the `CMakeLists.txt` file from pantheon-agent-polkit.

**Comment by davidmhewitt** [comment]
Fixed in #8
